apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: elyssa
  labels:
    app: frontend
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/shravya29m/elyssa-frontend:latest
          ports:
            - containerPort: 7860
          envFrom:
            - configMapRef:
                name: frontend-config
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 7860
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 7860
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
