apiVersion: v1
kind: Service
metadata:
  name: response-service
  namespace: elyssa
  labels:
    app: response-service
spec:
  selector:
    app: response-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: ClusterIP
