apiVersion: v1
kind: Service
metadata:
  name: sentiment-service
  namespace: elyssa
  labels:
    app: sentiment-service
spec:
  selector:
    app: sentiment-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
